import React, { Component } from 'react';
%PROP_TYPES_IMPORT%

%CSS_IMPORT%

class %COMPONENT_NAME% extends Component {
%INDENTATION%%HANDLERS%
%INDENTATION%%METHODS%
%INDENTATION%%LIFECYCLE_METHODS%
%INDENTATION%render() {
%INDENTATION%const %PROPS% = this.props;
%INDENTATION%%INDENTATION%return (
%INDENTATION%%INDENTATION%%INDENTATION%<div>

%INDENTATION%%INDENTATION%%INDENTATION%</div>
%INDENTATION%%INDENTATION%);
%INDENTATION%}
}

%PROP_TYPES_DEFINITION%
%DEFAULT_PROPS%
export default %COMPONENT_NAME%;
