# Note: "shell" would be more appropriate
language: python

before_install:
  - git clone https://github.com/bats-core/bats-core.git /tmp/bats
  - mkdir -p /tmp/local
  - bash /tmp/bats/install.sh /tmp/local
  - export PATH=/tmp/local/bin:$PATH

script: make test
