#!/usr/bin/env bash

#: TITLE: crc
#: DATE: 2019-04-23
#: VERSION: 0.1.0
#: AUTHOR: "Alex Y" <aleksandryackovlev@yandex.ru>
#: DESCRIPTION: Create React Component

crcDirectory="$HOME/.crc"

source "${crcDirectory}/bin/crc-env"
source "${crcDirectory}/bin/crc-create"
source "${crcDirectory}/bin/crc-config"
source "${crcDirectory}/bin/crc-template"
source "${crcDirectory}/bin/crc-help"
source "${crcDirectory}/bin/crc-utils"

commandToExec=$1
shift

case $commandToExec in
  create)
      crc-create "$@"
    ;;
  config)
      crc-config "$@"
    ;;
  template)
      crc-template "$@"
    ;;
  help)
      crc-help "$@"
    ;;
  *)
      crc-utils die "$(crc-env misuseErrorCode)" "An unknown command ""$commandToExec"
    ;;
esac
